-- 在线支付订单表（员工端在线缴费）
CREATE TABLE IF NOT EXISTS pay_order (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  order_no VARCHAR(40) NOT NULL COMMENT '业务订单号',
  fee_id BIGINT DEFAULT NULL COMMENT '关联账单ID',
  room_id BIGINT DEFAULT NULL COMMENT '房间ID',
  employee_id BIGINT DEFAULT NULL COMMENT '缴费员工ID',
  amount DECIMAL(10,2) DEFAULT 0.00 COMMENT '支付金额',
  month VARCHAR(20) DEFAULT NULL COMMENT '账单月份',
  channel VARCHAR(20) DEFAULT 'mock' COMMENT '支付渠道: mock/wechat/alipay',
  status VARCHAR(20) DEFAULT 'PENDING' COMMENT '状态: PENDING/SUCCESS/CLOSED',
  subject VARCHAR(100) DEFAULT NULL COMMENT '商品标题',
  out_trade_no VARCHAR(64) DEFAULT NULL COMMENT '渠道方交易号',
  paid_time DATETIME DEFAULT NULL COMMENT '支付完成时间',
  expire_time DATETIME DEFAULT NULL COMMENT '订单过期时间',
  callback_payload TEXT DEFAULT NULL COMMENT '渠道回调原文(留档)',
  remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
  creator VARCHAR(50) DEFAULT NULL,
  create_time DATETIME DEFAULT NULL,
  updater VARCHAR(50) DEFAULT NULL,
  update_time DATETIME DEFAULT NULL,
  deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
  tenant_id BIGINT DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_no (order_no),
  KEY idx_fee_id (fee_id),
  KEY idx_employee_id (employee_id),
  KEY idx_status (status),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='在线支付订单';